### ISSUE TITLE
Unresolvable holders for proxies

### ISSUE THREAD

**Issue by WardLT** [proxystore/proxystore#107]
### Describe the Request

There are points in using proxystore when I want to create a proxy and then be confident it won't accidentally get resolved on that system. Could we create a wrapper for an object that allows access to a resolvable Proxy but cannot be resolved itself? That would allow me to hold on to the proxy in a container that I know will never suddenly behave like the unresolved object?

### Sample Code

```python
safe_proxy = store.safe_proxy(my_obj)  # New way of creating a "safe proxy" ...
assert not isinstance(safe_proxy, type(my_obj))  # that oes not act like a proxy
proxy = safe_proxy.access_proxy()  # But can provide easy access to the "real" proxy ...
assert isinstance(proxy, type(my_obj)) # that acts like an object proxy
```

**Comment by gpauloski** [comment]
I like this idea! Especially if the proxy is passed through third-party code where you cannot guarantee what happens to it.

The wrapper should be pretty straightforward. We can override `__getattr__` to raise an exception if someone tries to improperly access the proxy.
```Python
class ProxyLocker(Generic[T]):
    def __init__(self, proxy: Proxy[T]) -> None:
        self._proxy = proxy

    def __getattr__(self, attr: str) -> Any:
        if attr == '_proxy':
            raise AttributeError('Cannot access proxy attribute of a Locker')
        return super().__getattr__(attr)

    def unlock(self) -> Proxy[T]:
        return super().__getattr__('_proxy')
```

(I'm using "lock/locker" here because it feels more narrowly defined than "safe.")

On the `Store` side, it should also be simple:

```Python
class Store:
    ...

    def locked_proxy(self, obj: T, ...) -> ProxyLocker[T]:
        return ProxyLocker(self.proxy(obj, ...))

    ...
```

I can add this this week.
