### ISSUE TITLE
Special Proxies for Hard-to-Serialize Objects

### ISSUE THREAD

**Issue by WardLT** [proxystore/proxystore#146]
### Describe the Request

Some objects, like Tensorflow and PyTorch models, require special serialization operations to send them between systems. Having ProxyStore identify such objects during serialization and use object-specific serialization routines.

**Comment by gpauloski** [comment]
Are you referring to `torch.save()/load()` for PyTorch and `tf.keras.Model().save()/load_model()` for TensorFlow? I think generally there's no way to infer the "correct" serialization method. You could have a lookup table but that requires constant update and for ProxyStore to pull in the dependencies for every custom type in the table. 

If you have another idea do let me know. Otherwise, I think the best alternative would be to allow users to supply a `serializer: Callable[[Any], bytes]` to `Store.set()`, `deserializer: Callable[[bytes], Any]` to `Store.get()`, and both to `Store.proxy()`. (This would replace the existing `serialize`/`deserialize` flags.)

For `proxy()`, the `serializer` would be used when creating the proxy of the object, and the `deserializer` would be included in the `Factory` inside the `Proxy` itself.

By default, the values for `serializer`/`deserializer` would just be ProxyStore's provided serialization functions, but users can create their own implementations as needed.

Example:
```python
import torch
import io

import proxystore.store

def serialize_torch_model(model: torch.nn.Module) -> bytes:
    buffer = io.BytesIO()
    torch.save(model, buffer)
    return buffer.read()

mymodel = torch.nn.Module()

store = proxystore.store.init_store(...)
key = store.set(mymodel, serializer=serialize_torch_model)
```

**Comment by WardLT** [comment]
Sounds great. I think the idea of allowing for user-supplied serialization functions would be a good way to service this need w/o adding much library-specific bloat to ProxyStore.

I'd imagine that we could add examples in the documentation or submodules labeled "external" if we found many users running into serialization problems.
