### ISSUE TITLE
ProxyStore Hangs on Midway2 Compute Node

### ISSUE THREAD

**Issue by ncollier** [proxystore/proxystore#209]
### Describe the problem.

Proxystore appears to be hanging while resolving a proxy when running on a compute node on University of Chicago's Midway2, using globus. Same code works as expected on a login node.

 I'm using funcx to execute a function on the compute node where one of the arguments is a proxy created on my local laptop. I can see via the globus web interface that the proxy object has been successfully transferred. If I pass the object itself (a numpy array) rather than the proxy to the function, everything works as expected on the compute node.

Midway2's compute nodes don't have network access to the internet, if that's relevant here.

The example below reproduces the problem.  

```python
globus_config = {
    # midway
    'af7bda53-6d04-11e5-ba46-22000b92c6ec': {
      'host_regex': 'midway2-[0-9]{1,4}\.rcc\.local',
      'endpoint_path': '~/proxy-store',
      'local_path':'~/proxy-store'
    },

    "957f111a-a242-11ed-a2a4-8383522b48d9": {
      "host_regex": "MacBook-Pro\.local",
      "endpoint_path": "~/proxy-store",
      "local_path": "~/proxy-store"
  }
}

endpoints = GlobusEndpoints.from_dict(globus_config)
store = GlobusStore('globus', endpoints=endpoints)
x = np.random.rand(4, 4)
p = store.proxy(x)

midway_compute = '4190440c-bac3-4890-a2ef-40eccb4f51a5'

def x2(x):
    return 2 * x

with funcx.FuncXExecutor(endpoint_id=midway_compute) as fx:
    ft = fx.submit(x2, p)
    print(ft.result())
```

Thanks.

### How did you install ProxyStore?

```console
pip install proxystore
```

### ProxyStore Version

0.4.0

### Python Version

3.9

### OS and Platform

x86 Linux

**Comment by gpauloski** [comment]
Hi, @ncollier! Appreciate the reproducer.

Internally, a `GlobusStore` proxy will call the Globus SDK's [`task_wait()`](https://globus-sdk-python.readthedocs.io/en/stable/services/transfer.html#globus_sdk.TransferClient.task_wait) method to verify the transfer completed successfully before attempting to read the object from disk. Since Midway's compute nodes don't allow internet access, you are probably getting stuck in that polling.

It should, however, raise a `RuntimeError` after waiting for 60 seconds (the default), so I will look into why you are hanging rather than seeing an exception.

As far as I'm aware there's no workaround on Midway like the HTTP proxies at ALCF. I do have two alternative ideas:
1. Extend `GlobusStore` and override [`exists()`](https://github.com/proxystore/proxystore/blob/5ee42ae2e7f093d1662e5b06b77ec7bceb88a05c/proxystore/store/globus.py#L512) to poll the filesystem for the existence of the file rather than calling `GlobusStore._wait_on_tasks()` (which calls `task_wait()`). This solution will not work in the reverse direction, e.g., a FuncX worker sending a `GlobusStore` proxy as the result back to the client.
2. We have an experimental system called [ProxyStore Endpoints](https://docs.proxystore.dev/main/guides/endpoints/) that work similarly to FuncX Endpoints in that they live on login nodes (so should have internet access) and processes on compute nodes connect back to the endpoint on the login node. If you are interested in trying that out, I'm happy to chat more. Setting them up is very similar to FuncX Endpoints, and the [`EndpointStore`](https://docs.proxystore.dev/main/reference/store/endpoint/#proxystore.store.endpoint.EndpointStore) just takes a list of your (probably) two ProxyStore Endpoint UUIDs. You will need a "signaling server" URL which I can share with you over slack (we are not hosting it publicly yet).

**Comment by gpauloski** [comment]
I confirmed the hanging is happening when the Globus SDK attempts to open a connection to the Globus SDK. (Similarly, all HTTP/S requests on Midway compute notes hang rather than returning a "not available" error like on ALCF compute nodes.)

I could add some wrapper logic to cancel the API request after the timeout so the failure is more graceful than hanging. That may not be worth the time given it still doesn't make the `GlobusStore` usable in this kind of environment.

Including the code I used to reproduce w/o FuncX here for future reference:
```python
from proxystore.store.globus import GlobusEndpoints
from proxystore.store.globus import GlobusStore
from proxystore.store.globus import GlobusStoreKey

globus_config = {
  "9032dd3a-e841-4687-a163-2720da731b5b": {
    "host_regex": "theta.*",
    "endpoint_path": "/~/proxystore-dump",
    "local_path": "~/proxystore-dump"
  },
  "af7bda53-6d04-11e5-ba46-22000b92c6ec": {
    "host_regex": "midway2.*",
    "endpoint_path": "/~/proxystore-dump",
    "local_path": "~/proxystore-dump"
  }
}

# On Theta
endpoints = GlobusEndpoints.from_dict(globus_config)
store = GlobusStore('globus', endpoints=endpoints)
key = store.set('test value')
print(key)

# On Midway
key = GlobusStoreKey('...', '...')  # Copy over key from Theta
store = GlobusStore('globus', endpoints=endpoints)
store.get(key)
```

**Comment by ncollier** [comment]
Thanks for the quick response. I suspect that most of our use cases involve sending a proxy to the compute node, rather than returning one as result. So, perhaps the `exists()` solution would work for us, and we will keep that in mind. I'll also check out the ProxyStore Endpoints docs as well.

**Comment by gpauloski** [comment]
It turns out you can redirect the Globus Transfer service URL with environment variables: https://globus-sdk-python.readthedocs.io/en/stable/config.html?highlight=environment#environment-variables. You can set your jobs to open an SSH tunnel back to the login node and set the `GLOBUS_SDK_SERVICE_URL_TRANSFER` variable.

It will probably look like:
```bash
ssh -L 12345:localhost:443 midway2-login1 -fN  # probably need to configure ssh key
export GLOBUS_SDK_SERVICE_URL_TRANSFER="https://localhost:12345"
export GLOBUS_SDK_VERIFY_SSL="false"
```

You could also configure this in the `worker_init` of your FuncX endpoint.
