### ISSUE TITLE
Potential bug: Proxying Proxies

### ISSUE THREAD

**Issue by WardLT** [proxystore/proxystore#215]
### Describe the problem.

I have a workflow which makes extensive uses of proxies where I receive a result then pass it to subsequent tasks. I haven't hit this problem, but @gpauloski and I recognize that if I'm not careful and make a Proxy of a Proxy then strange bugs may follow:
- If the first proxy is evicted then its proxy will be impossible to resolve
- If the first proxy uses a different Store/Connection than the second, then it may be unresolvable.

### How did you install ProxyStore?

```console
pip install proxystore
```

### ProxyStore Version

v0.4.1

### Python Version

3.10

### OS and Platform

x86 Linux

**Comment by gpauloski** [comment]
Thanks for opening this, @WardLT. It'll be helpful to have this issue to refer back to. After mulling on this, I'm increasingly of the opinion that there is nothing unique to be considered with nested proxies.

Given a stored object `x` and any number of proxies `p` of `x`, ProxyStore currently leaves it to the user to guarantee that the lifetime `x` is greater than or equal to all `p` lifetimes. Similarly, given any number of proxies `p` and the corresponding store `s`, it is also the responsibility of the user to ensure the lifetime of any `p` is greater than or equal to that of `s`. In other words, ProxyStore has no mechanism to say "don't evict this object" or "don't close this store" if a proxy corresponding to said object or store still exists.

With respect to the two potential bugs with nested proxies you mention, they violate the above assumptions.

### Potential Bug 1

> If the first proxy is evicted then its proxy will be impossible to resolve

I think this is functionally equivalent to the problem of two separate proxies referring to the same object. If one proxy evicts the object before the second proxy is resolved, the second proxy will be unable to ever resolve itself.

*Potential Solution 1:* Some form of global reference counting to prevent evicting of an object if references (i.e., proxies) still exist of it. This is challenging to do in an efficient way that does not require some singular, global state hosted somewhere accessible by all proxies.

*Potential Solution 2:* I have also considered Rust borrow-like semantics for proxies. I.e., a store can produce either (1) many immutable proxies (`evict=False`) or (2) a single mutable proxy (`evict=True`). This could allow us to make strong guarantees about resolvability of a given proxy (assuming the underlying store is always available), but the programming now has to be more careful about how they create and replicate proxies.

Though, since I argue that this potential bug is an artifact of the guarantees that the user must uphold, I think these two potential solutions fall into the category of potential enhancements in the future rather than bug fixes. Both are technically very challenging.

### Potential Bug 2

> If the first proxy uses a different Store/Connection than the second, then it may be unresolvable.

There is always a concern that a proxy could end up in a location where it cannot access the store that created it. It does seem reasonable to say that it is more likely that one would unknowingly end up in this position when using nested proxies, but I do not think this is a separate problem. 

*Potential Solution:* A better store option which eliminates the need for using multiple distinct stores. This is on our roadmap, but is a much more ambitious, longer-term next step.

### Conclusion

Are these answers satisfying 😄? I suspect many would say no. I do view it as a limitation of ProxyStore that the guarantees of resolvability are not enforceable and require some consideration from the user, but I think its a price we pay for flexibility.

**Comment by gpauloski** [comment]
Going to close for now until we have some actionable items regarding this.

**Comment by gpauloski** [comment]
Going to close for now until we have some actionable items regarding this.
