### ISSUE TITLE
Storing additional object metadata in proxy

### ISSUE THREAD

**Issue by ValHayot** [proxystore/proxystore#49]
### Describe the Request

Would be nice to be able to retrieve additional object metadata (e.g., size) within the proxy without having to resolve the object from store first.

### Sample Code

```python
store = ps.store.init_store(...)
p = store.proxy(x)
p.bsize() # Number of bytes the serialized data occupies
p.size() # python object size
```

**Comment by gpauloski** [comment]
A bit of a long response because I anticipate this feature becoming more important overtime.

### Where does metadata of a target object go?

Adding attributes to a proxy object is not possible because of how `Proxy.__getattr__` is implemented. (Maybe you could modify `Proxy.__getattr__` but then there is another issue that you risk attribute names of the *target* colliding with custom attributes added by ProxyStore.)

The recommended way to achieve this functionality (access metadata of a proxy without resolving) is to store the additional metadata in the factory.

```
store = ps.store.init_store(...)
p = store.proxy(x)
p.__factory__.bsize() # Number of bytes the serialized data occupies
p.__factory__.size() # python object size
```

### How to store metadata in the factory?

Currently, any attributes added to a `StoreFactory` will not be serialized when the corresponding proxy is serialized (because some things in the factory should not be serialized). So this is not possible:
```
p = store.proxy(x)
p.__factory__.bsize = ...
# Serialize and send p to another process
p.__factory__.bsize  # raises AttributeError
```

We could have [`StoreFactory`](https://github.com/gpauloski/proxystore/blob/fbc0965cb956c6683ddfd92784aa8d2aa3542c1e/proxystore/store/base.py#L37) take `**kwargs` and set any additional kwargs as attributes that should be serialized.
Then we also add a `proxystore.proxy.get_factory(proxy: Proxy) -> Factory` function so we are not accessing `__factory__` directly so the resulting usage would look like:
```
store = ps.store.init_store(...)
p = store.proxy(x)  # Overridden to pass relevant attributes to StoreFactory
ps.proxy.get_factory(p).bsize  # Number of bytes the serialized data occupies
ps.proxy.get_factory(p).size  # python object size
```

This solution is simple and works, but I don't like dynamically adding attributes because type checking is no longer possible and it's not clear when reading code what attributes the factory may or may not have.

### Customizable Keys?

The factory already contains a `key` attribute so a better long term solution may be to make keys more powerful/complete. I.e., the key is a data stucture that contains all metadata needed about a *target*.

For example, if keys are dataclasses, each `Store` type can have an associated `StoreKey` type. E.g.,
```
@dataclass
class RDMAStoreKey():
    key: str
    bsize: int
    size: int
    ...

@dataclass
class GlobusStoreKey():
    filename: str
    transfer_id: UUID
```

I need to think about this more but it seems to achieve the goals of including metadata of the *target* in the proxy/factory and makes the key the single source of "what do I need to know to figure out where this data is?"

Otherwise, the function signature of `Store.get()`/`Store.get()` would get more complicated as more information is needed about an object. (For example, in `GlobusStore`, we get around this by making the str key encode the filename and Globus transfer ID so we don't change the function signatures.)

What do you think about this? Please feel free to push back.

**Comment by ValHayot** [comment]
I think creating a key dataclass sounds like a good idea. I'm just wondering if altering the data (e.g. appending data, and therefore changing its size) would affect the key's ID in this scenario. Otherwise, I think it's a good idea.

Before you make any changes, however, I'll try to collect data on the impacts of metadata accesses, just to get an idea on how much worse current metadata accesses can be even in the most optimal scenarios.
