### ISSUE TITLE
Proxy for a `Dict` is not a `Mapping`

### ISSUE THREAD

**Issue by Zilinghan** [proxystore/proxystore#583]
```python
from torch import nn
from typing import Mapping
from proxystore.store import Store, get_store
from proxystore.connectors.redis import RedisConnector

store = Store(
    'my-store',
    RedisConnector(hostname='localhost', port=6379),
    register=True,
)

store = get_store('my-store')  

# Define a test model 
model = nn.Sequential(
    nn.Conv2d(1, 20, 5),
    nn.ReLU(),
    nn.Conv2d(20, 64, 5),
    nn.ReLU()
)

state_dict = model.state_dict()
print(isinstance(state_dict, Mapping))                  # True
state_dict_proxy = store.proxy(state_dict)
print(isinstance(state_dict_proxy, type(state_dict)))   # True
print(isinstance(state_dict_proxy, Mapping))            # False
model.load_state_dict(state_dict_proxy)                 # Error
```

For a python dictionary, when I create a proxy for that, `isinstance(state_dict_proxy, Mapping)` gives `False`. As a result, I cannot use `model.load_state_dict(state_dict_proxy)`, which has the above assertion to load the model parameters and gives the following error

```bash
Traceback (most recent call last):
  File "<path>/proxy.py", line 27, in <module>
    model.load_state_dict(state_dict_proxy)
  File "<path>/module.py", line 1994, in load_state_dict
    raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
TypeError: Expected state_dict to be dict-like, got <class 'Proxy'>.
```

**Comment by gpauloski** [comment]
Hi, @Zilinghan! Thanks for the reproducer! We have encountered this issue as well. The quick fix is to extract the target value of the proxy right before `model.load_state_dict()`:
```python
from proxystore.proxy import extract, Proxy

if isinstance(state_dict, Proxy):
    state_dict = extract(state_dict)
    
model.load_state_dict(state_dict)
```

That said, it is strange that `dict` and `Mapping` behave differently so I'll have to dig into the differences. I've recently made some changes to improve static and runtime type checking on proxies, so maybe there are some avenues through which this could be fixed.

I'll try some things out and get back to you, but in the meantime the above fix with [`extract()`](https://docs.proxystore.dev/main/api/proxy/#proxystore.proxy.extract) will address the error.

**Comment by Zilinghan** [comment]
@gpauloski Thanks for the quick response, and `extract` helps me resolve the problem.

**Comment by gpauloski** [comment]
I dug into the issue a bit further and found that `collections.abc.Mapping` works even though `typing.Mapping` does not.
```python
import collections
import typing
from proxystore.proxy import Proxy

my_dict_proxy = Proxy(lambda: {})
assert isinstance(my_dict_proxy, dict)
assert not isinstance(my_dict_proxy, typing.Mapping)
assert isinstance(my_dict_proxy, collections.abc.Mapping)
```
`typing.Mapping` is an alias for `collections.abc.Mapping`, but the alias class ([`_BaseGenericAlias`](https://github.com/python/cpython/blob/3.11/Lib/typing.py#L1327-L1328)) essentially ends up calling `type(proxy)` and checks [`issubclass(Proxy, Mapping)`](https://github.com/python/cpython/blob/1b0e63c81b54a937b089fe335761cba4a96c8cdf/Lib/typing.py#L1606) which will always fail. The `typing.Mapping` and other aliases are deprecated, so I'm just going to add a section to the doc's FAQ suggesting users to prefer `collections.abc` over `typing` for deprecated aliases.

Of course, this doesn't help you much since you can't control the source of `Module.load_state_dict()` which uses `typing.Mapping`. Hopefully they upgrade this once Python 3.8 support is dropped from PyTorch, but in the meantime I think `extract()` is the only option for your example.

**Comment by Zilinghan** [comment]
Hi @gpauloski, I encountered another error related to bytes
```python
import pickle
from proxystore.store import Store, get_store
from proxystore.connectors.redis import RedisConnector

store = Store(
    'my-store',
    RedisConnector(hostname='localhost', port=6379),
    register=True,
)

store = get_store('my-store')  

dict = {
    'key1': 'value1',
    'key2': 'value2'
}

dict_bytes = pickle.dumps(dict)

dict_proxy = store.proxy(dict_bytes)


print(pickle.loads(dict_proxy)) # Error
```

**Comment by gpauloski** [comment]
Hi, @Zilinghan!

This error is not related to creating a `Proxy` of `bytes`, but actually because `pickle.loads()` is a [binding to a C function](https://github.com/python/cpython/blob/1b0e63c81b54a937b089fe335761cba4a96c8cdf/Lib/pickle.py#L1777-L1787). The `Proxy` type is generally not compatible with functions written in non-Python. This limitation is noted in the [`Proxy` docstring](https://docs.proxystore.dev/latest/api/proxy/#proxystore.proxy.Proxy) using an example with `io.StringIO`.

That said, `store.proxy()` will serialize your object anyways (using pickle, with a fallback to cloudpickle) so I would generally recommend against this specific pattern. If you would like to serialize your object yourself and customize the deserializing of the proxy, I would suggest using the `serializer`/`deserializer` options.

```python
import pickle
from proxystore.store import Store
from proxystore.connectors.local import LocalConnector

with Store('my-store', LocalConnector(), register=True) as store:
    data = {
        'key1': 'value1',
        'key2': 'value2',
    }

    data_bytes = pickle.dumps(data)

    data_proxy = store.proxy(
        data_bytes,
        # dict_bytes is already serialized so pass a no-op serializer function
        serializer=lambda s: s,
        # use pickle.loads when resolving the proxy
        deserializer=pickle.loads,
        # necessary when serializing objects yourself
        populate_target=False,
    )

    print(data_proxy)  # prints {'key1': 'value1', 'key2': 'value2'}
```

As I mentioned, ProxyStore will pickle data for you, but there are certainly cases where you may prefer using alternate serializers. The docs for  [Serialization in the `Store`](https://docs.proxystore.dev/latest/concepts/store/?h=serializer#serialization) discuss this further.
